FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends gcc libpq-dev && rm -rf /var/lib/apt/lists/*
COPY requirements.django.txt .
RUN pip install --no-cache-dir -r requirements.django.txt
COPY apps/    ./apps/
COPY config/  ./config/
COPY manage.py   ./manage.py
CMD ["daphne", "-b", "0.0.0.0", "-p", "8080", "config.asgi:application"]
