# Generated by Django 6.0.2 on 2026-02-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=50, unique=True)),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('upvote_ratio', models.FloatField(blank=True, null=True)),
                ('num_comments', models.IntegerField(default=0)),
                ('created_utc', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('priority', models.CharField(max_length=10)),
                ('poll_interval', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('score', models.IntegerField()),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('created_utc', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.subreddit'),
        ),
        migrations.CreateModel(
            name='KeywordTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.subreddit')),
            ],
        ),
        migrations.CreateModel(
            name='SubredditStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_posts', models.IntegerField()),
                ('total_comments', models.IntegerField()),
                ('top_user', models.CharField(blank=True, max_length=100, null=True)),
                ('subreddit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reddit.subreddit')),
            ],
        ),
    ]
