# Generated by Django 6.0.2 on 2026-02-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subreddit',
            options={'managed': False},
        ),
    ]
