# Generated by Django 6.0.2 on 2026-02-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_alter_post_options_alter_subreddit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubredditConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Subreddit name without the r/ prefix, e.g. 'technology'", max_length=100, unique=True)),
                ('interval_seconds', models.PositiveIntegerField(default=120, help_text='How often (seconds) the scheduler fetches new posts from this subreddit')),
                ('priority', models.CharField(choices=[('fast', 'Fast   (~30s interval)'), ('medium', 'Medium (~2min interval)'), ('slow', 'Slow   (~10min interval)')], default='medium', help_text='Processing priority tier passed to the Kafka producer', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to pause ingestion without deleting the record')),
                ('added_by', models.CharField(blank=True, help_text='Free-text: who added this subreddit (informal audit trail)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subreddit Config',
                'verbose_name_plural': 'Subreddit Configs',
                'db_table': 'subreddit_config',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='keywordtrend',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subredditstats',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
        migrations.AlterModelTable(
            name='subreddit',
            table='subreddits',
        ),
    ]
