# Generated by Django 6.0.2 on 2026-02-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_subredditconfig_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
        migrations.AlterModelTable(
            name='keywordtrend',
            table='keyword_trends',
        ),
        migrations.AlterModelTable(
            name='subredditstats',
            table='subreddit_stats',
        ),
    ]
