# Generated by Django 6.0.2 on 2026-03-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField()),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'communities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformDivergence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('detected_at', models.DateTimeField()),
                ('platform_a', models.TextField()),
                ('platform_b', models.TextField()),
                ('sentiment_a', models.FloatField()),
                ('sentiment_b', models.FloatField()),
                ('divergence_score', models.FloatField()),
                ('origin_platform', models.TextField(null=True)),
                ('origin_lag_minutes', models.IntegerField(null=True)),
                ('sample_signal_ids', models.JSONField(default=list)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'platform_divergence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('platform', models.TextField()),
                ('source_id', models.TextField()),
                ('title', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('author', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('raw_score', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('normalised_score', models.FloatField(null=True)),
                ('score_velocity', models.FloatField(null=True)),
                ('comment_velocity', models.FloatField(null=True)),
                ('trending_score', models.FloatField(default=0.0)),
                ('is_trending', models.BooleanField(default=False)),
                ('sentiment_compound', models.FloatField(null=True)),
                ('sentiment_label', models.TextField(null=True)),
                ('keywords', models.JSONField(default=list)),
                ('topics', models.JSONField(default=list)),
                ('extra', models.JSONField(default=dict)),
                ('schema_version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'signals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField(choices=[('reddit', 'Reddit'), ('hackernews', 'Hacker News'), ('bluesky', 'Bluesky'), ('youtube', 'YouTube')])),
                ('identifier', models.TextField()),
                ('label', models.TextField(blank=True)),
                ('interval_seconds', models.PositiveIntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.TextField(blank=True, default='system')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source_config',
                'ordering': ['platform', 'identifier'],
                'managed': False,
            },
        ),
    ]
